import { CharacterRow } from '../config/supabase';
import { Character } from '../types/Character';

export function convertFromSupabase(row: CharacterRow): Character {
  return {
    name: row.name,
    gender: row.gender as 'male' | 'female',
    seed: row.seed,
    level: row.level,
    hp: row.hp,
    maxHp: row.max_hp,
    strength: row.strength,
    vitality: row.vitality,
    dexterity: row.dexterity,
    luck: row.luck,
    intelligence: row.intelligence,
    focus: row.focus,
    experience: row.experience,
    wins: row.wins,
    losses: row.losses,
    fightsLeft: row.fights_left,
    pveFightsLeft: row.pve_fights_left ?? 5,
    lastFightReset: row.last_fight_reset,
    fightHistory: row.fight_history,
    foughtToday: row.fought_today,
    statPoints: row.stat_points,
    pendingFight: row.pending_fight ?? undefined,
    inventory: row.inventory,
    lastLootRoll: row.last_loot_roll,
    lootboxStreak: row.lootbox_streak ?? 0,
    incomingFightHistory: row.incoming_fight_history,
    isBot: row.is_bot,
    autoMode: row.auto_mode,
    equippedItems: row.equipped_items ?? { weapon: null, armor: null, accessory: null },
    id: row.id,
    lastIdleCheck: row.last_idle_check ? new Date(row.last_idle_check).getTime() : 0,
    lastActive: row.last_active ? new Date(row.last_active).getTime() : 0,
    idleStreak: row.idle_streak ?? 0,
    idleMaxStreak: row.idle_max_streak ?? 0,
    idleTotalKills: row.idle_total_kills ?? 0,
    idleTotalXp: row.idle_total_xp ?? 0,
    essence: row.essence ?? 0,
    itemUpgrades: row.item_upgrades ?? undefined,
  };
}

export function convertToSupabase(character: Character): Partial<CharacterRow> {
  return {
    name: character.name,
    gender: character.gender as 'male' | 'female',
    seed: character.seed,
    level: character.level,
    hp: character.hp,
    max_hp: character.maxHp,
    strength: character.strength,
    vitality: character.vitality,
    dexterity: character.dexterity,
    luck: character.luck,
    intelligence: character.intelligence,
    focus: character.focus ?? 10,
    experience: character.experience ?? 0,
    wins: character.wins ?? 0,
    losses: character.losses ?? 0,
    fights_left: character.fightsLeft ?? 5,
    pve_fights_left: character.pveFightsLeft ?? 5,
    last_fight_reset: character.lastFightReset ?? Date.now(),
    fight_history: character.fightHistory ?? [],
    fought_today: character.foughtToday ?? [],
    stat_points: character.statPoints ?? 0,
    pending_fight: character.pendingFight ?? null,
    inventory: character.inventory ?? [],
    last_loot_roll: character.lastLootRoll ?? 0,
    lootbox_streak: character.lootboxStreak ?? 0,
    incoming_fight_history: character.incomingFightHistory ?? [],
    is_bot: typeof character.isBot === 'boolean' ? character.isBot : false,
    auto_mode: character.autoMode ?? false,
    equipped_items: character.equippedItems ?? { weapon: null, armor: null, accessory: null },
    last_idle_check: character.lastIdleCheck ? new Date(character.lastIdleCheck).toISOString() : null,
    last_active: character.lastActive ? new Date(character.lastActive).toISOString() : null,
    idle_streak: character.idleStreak ?? 0,
    idle_max_streak: character.idleMaxStreak ?? 0,
    idle_total_kills: character.idleTotalKills ?? 0,
    idle_total_xp: character.idleTotalXp ?? 0,
    essence: character.essence ?? 0,
    item_upgrades: character.itemUpgrades ?? null,
  };
}
